const mongoose = require("mongoose");

const staffSchema = new mongoose.Schema(
  {
    staff_id: { type: String, required: true, unique: true },
    school_id: { type: String, required: true },
    full_name: { type: String, required: true },
    email: { type: String, required: true },
    phone: { type: String, default: null },
    alternate_phone: { type: String, default: null },
    position: { type: String, default: null },
    job_title: { type: String, default: null },
    department: { type: String, default: null },
    qualification: { type: String, default: null },
    experience_years: { type: Number, default: 0 },
    employment_type: { type: String, default: null },
    employment_status: { type: String, default: "active" },
    record_status: { type: String, default: "active" },
    role: { type: String, default: null },
    salary: { type: Number, default: null },
    salary_grade: { type: String, default: null },
    joining_date: { type: String, default: null },
    confirmation_date: { type: String, default: null },
    date_of_birth: { type: String, default: null },
    gender: { type: String, default: null },
    religion: { type: String, default: null },
    marital_status: { type: String, default: null },
    nationality: { type: String, default: null },
    state_of_origin: { type: String, default: null },
    address: { type: String, default: null },
    blood_group: { type: String, default: null },
    genotype: { type: String, default: null },
    medical_conditions: { type: String, default: null },
    staff_photo: { type: String, default: null },
    national_id: { type: String, default: null },
    tax_number: { type: String, default: null },
    bank_name: { type: String, default: null },
    bank_account: { type: String, default: null },
    emergency_contact_name: { type: String, default: null },
    emergency_contact_phone: { type: String, default: null },
    emergency_contact_relationship: { type: String, default: null },
    emergency_contact_address: { type: String, default: null },
    next_of_kin_name: { type: String, default: null },
    next_of_kin_phone: { type: String, default: null },
    next_of_kin_relationship: { type: String, default: null },
    next_of_kin_address: { type: String, default: null },
    two_factor_auth: { type: Boolean, default: false },
    is_active: { type: Boolean, default: true },
    created_by: { type: String, default: null },
    updated_at: { type: Date, default: Date.now },
  },
  { timestamps: { createdAt: "created_at", updatedAt: false } }
);

module.exports = mongoose.model("Staff", staffSchema);
